import { makeContentProxy } from "../i18n"

const ZH = {
  context: {
    description_profile_count: "{count} 份画像",
    description_existing_session: "已有会话",
    description_manual_target: "手动指定目标",
    toast_profile_deleted: "公司画像已删除",
    toast_export_done_title: "画像包已导出",
    toast_scan_done_title: "画像包已扫描",
    toast_scan_done_with_conflicts: "发现 {count} 家冲突公司，需要你确认",
    toast_scan_done_no_conflicts: "共 {count} 家公司，可直接导入",
    toast_import_done_title: "画像导入完成",
    toast_import_done_summary: "新增 {imported} 家，替换 {replaced} 家，跳过 {skipped} 家",
  },
  detail: {
    empty_title: "先选择目标用户",
    empty_description: "左侧先选一个用户空间，右侧才能查看、导出或导入公司画像。",
    space_label: "画像空间",
    company_count: "{count} 家公司",
    current_viewing: "当前查看：{title}",
    exporting_button: "导出中…",
    export_button: "导出当前空间",
    import_button: "导入画像包",
    delete_confirm: "确定彻底删除 {title} 的公司画像吗？",
    deleting_button: "删除中…",
    delete_button: "删除画像",
    company_list_label: "公司画像（{count}）",
    updated_badge: "更新",
    import_done_title: "导入完成",
    import_done_summary: "新增 {imported} 家，替换 {replaced} 家，跳过 {skipped} 家。",
    download_backup_button: "下载导入前备份",
    package_loaded_title: "画像包已载入",
    package_loaded_summary: "共 {profiles} 家公司，发现 {conflicts} 家冲突公司。",
    reselect_package_button: "重新选择画像包",
    cancel_import_button: "取消本次导入",
    scan_result_title: "导入扫描结果",
    scan_total: "画像总数：{count}",
    scan_importable: "可直接导入：{count}",
    scan_need_confirm: "需要确认：{count}",
    no_conflicts_title: "当前空间没有冲突，可以直接导入。",
    no_conflicts_description: "这次会导入 {count} 家公司画像。",
    conflicts_title: "冲突审阅",
    conflicts_description: "只需要决定这些已存在的公司要保留当前版本，还是改成导入版本。",
    keep_all_button: "全部保留当前",
    replace_all_button: "全部用导入版本替换",
    side_existing_title: "你当前的版本",
    side_imported_title: "导入版本",
    keep_button: "保留我当前的",
    replace_button: "用导入版本替换",
    importing_button: "导入中…",
    start_import_button: "开始导入",
    pick_company_title: "先选择一家公司",
    empty_space_title: "这个空间还没有公司画像",
    pick_company_description: "上面已经列出这个空间里的公司，点一家公司就能查看详情。",
    empty_space_description: "可以直接导入别人整理好的画像包，或者让 agent 为这个用户新建首份公司画像。",
    pick_package_button: "选择画像包",
    main_file_title: "画像主文件",
    main_file_subtitle: "直接展示当前目录中的 `profile.md`",
    events_title: "事件文件",
    events_count: "{count} 条事件",
    events_empty: "当前目录下还没有事件文件。",
    summary_updated_at: "更新于：{date}",
    summary_event_count: "{count} 条事件",
    summary_no_mainline: "未提取到投资主线摘要",
    date_unknown: "—",
  },
}

const EN: typeof ZH = {
  context: {
    description_profile_count: "{count} profiles",
    description_existing_session: "Existing session",
    description_manual_target: "Manually specified target",
    toast_profile_deleted: "Company profile deleted",
    toast_export_done_title: "Profile package exported",
    toast_scan_done_title: "Profile package scanned",
    toast_scan_done_with_conflicts: "{count} conflicting companies — please confirm",
    toast_scan_done_no_conflicts: "{count} companies, ready to import",
    toast_import_done_title: "Profile import complete",
    toast_import_done_summary: "Added {imported}, replaced {replaced}, skipped {skipped}",
  },
  detail: {
    empty_title: "Pick a target user first",
    empty_description: "Select a user space on the left to view, export, or import company profiles here.",
    space_label: "Profile space",
    company_count: "{count} companies",
    current_viewing: "Viewing: {title}",
    exporting_button: "Exporting…",
    export_button: "Export this space",
    import_button: "Import package",
    delete_confirm: "Permanently delete the company profile for {title}?",
    deleting_button: "Deleting…",
    delete_button: "Delete profile",
    company_list_label: "Company profiles ({count})",
    updated_badge: "Updated",
    import_done_title: "Import complete",
    import_done_summary: "Added {imported}, replaced {replaced}, skipped {skipped}.",
    download_backup_button: "Download pre-import backup",
    package_loaded_title: "Package loaded",
    package_loaded_summary: "{profiles} companies total, {conflicts} conflicting.",
    reselect_package_button: "Pick another package",
    cancel_import_button: "Cancel this import",
    scan_result_title: "Scan result",
    scan_total: "Profiles total: {count}",
    scan_importable: "Importable: {count}",
    scan_need_confirm: "Needs confirmation: {count}",
    no_conflicts_title: "No conflicts in this space — ready to import.",
    no_conflicts_description: "{count} company profiles will be imported.",
    conflicts_title: "Conflict review",
    conflicts_description: "Decide whether to keep the current version of each existing company or replace it with the imported version.",
    keep_all_button: "Keep all current",
    replace_all_button: "Replace all with imported",
    side_existing_title: "Your current version",
    side_imported_title: "Imported version",
    keep_button: "Keep mine",
    replace_button: "Replace with imported",
    importing_button: "Importing…",
    start_import_button: "Start import",
    pick_company_title: "Pick a company first",
    empty_space_title: "No company profiles in this space yet",
    pick_company_description: "The companies in this space are listed above — click one to see its detail.",
    empty_space_description: "Import a curated profile package, or let the agent build the first profile for this user.",
    pick_package_button: "Choose package",
    main_file_title: "Main profile file",
    main_file_subtitle: "Shows `profile.md` from the current directory",
    events_title: "Event files",
    events_count: "{count} events",
    events_empty: "No event files in the current directory yet.",
    summary_updated_at: "Updated: {date}",
    summary_event_count: "{count} events",
    summary_no_mainline: "No mainline excerpt extracted",
    date_unknown: "—",
  },
}

export const COMPANY_PROFILES = makeContentProxy(ZH, EN)
export const __COMPANY_PROFILES_TREES__ = { zh: ZH, en: EN } as const
