import { makeContentProxy } from "../i18n"

const ZH = {
  page: {
    title: "推送日志",
    window_label: "窗口",
    channel_label: "渠道",
    user_label: "用户",
    all_users: "全部用户",
    refresh_button: "刷新",
    refreshing_button: "刷新中…",
    summary_total: "24h 总数",
    summary_sent: "已发送",
    summary_failed: "发送失败",
    summary_skipped: "主动跳过",
    summary_duplicate: "重复拦截",
    summary_users: "覆盖用户",
    histogram_title: "24h 推送频率（每小时一桶，左→右 = 旧→新）",
    histogram_hour_suffix: "时",
    histogram_tooltip: "{ts}\n总 {total} · 发送 {sent} · 失败 {failed} · 跳过 {skipped}",
    legend_sent: "发送",
    legend_failed: "失败",
    legend_skipped: "跳过",
    list_caption: "推送记录（最多 {limit} 条，倒序）",
    list_count: "共 {count} 条",
    col_time: "时间",
    col_user: "用户",
    col_channel: "渠道",
    col_event: "事件类型",
    col_job: "任务",
    col_send_status: "发送状态",
    col_summary: "摘要",
    empty_records: "该窗口内没有匹配的推送记录。",
    drawer_close: "关闭",
    drawer_label_source: "来源",
    drawer_label_event_kind: "事件类型",
    drawer_label_user: "用户",
    drawer_label_channel: "渠道",
    drawer_label_channel_scope: "会话场景",
    drawer_label_target: "目标",
    drawer_label_exec_status: "执行状态",
    drawer_label_send_status: "发送状态",
    drawer_label_should_deliver: "投递判定",
    drawer_label_delivered: "实际投递",
    drawer_label_job_id: "任务 ID",
    drawer_response_preview: "响应预览",
    drawer_error: "错误",
    drawer_detail: "详情",
  },
  send_status: {
    all: "全部发送状态",
    sent: "已发送",
    dryrun: "Dry run",
    queued: "已排队",
    quiet_held: "勿扰暂存",
    filtered: "偏好过滤",
    capped: "上限降级",
    cooled_down: "冷却降级",
    price_capped: "价格上限降级",
    price_cooled_down: "价格冷却降级",
    omitted: "摘要省略",
    skipped_noop: "未发送（未命中/排队）",
    skipped_error: "未发送（执行失败）",
    send_failed: "发送失败",
    failed: "发送失败（事件）",
    target_resolution_failed: "目标解析失败",
    duplicate_suppressed: "已拦截重复发送",
  },
  exec_status: {
    all: "全部执行状态",
    completed: "执行成功",
    noop: "未命中",
    execution_failed: "执行失败",
  },
  channel: {
    all: "全部渠道",
    feishu: "飞书",
  },
  source: {
    cron: "定时任务",
    event: "事件",
  },
  event_kind: {
    earnings_upcoming: "财报预告",
    earnings_released: "财报发布",
    earnings_call_transcript: "财报电话会",
    news_critical: "重点新闻",
    price_alert: "价格异动",
    weekly52_high: "52周新高",
    weekly52_low: "52周新低",
    dividend: "分红",
    split: "拆股",
    sec_filing: "SEC 文件",
    analyst_grade: "分析师评级",
    macro_event: "宏观事件",
    social_post: "社媒动态",
  },
  prefs: {
    title: "通知偏好（按用户主体）",
    subtitle: "上区：一键启停，切换即保存；下区：选择一个用户主体细调严重度和事件类型范围",
    refresh_button: "刷新",
    actor_list_label: "用户主体列表",
    actor_loading: "加载中…",
    actor_empty: "还没有可选用户主体（手动输入下方字段或先让渠道产生一条消息）",
    saving_label: "保存中…",
    pushing_label: "已开启",
    off_label: "已关闭",
    summarize_disabled: "已关闭",
    summarize_enabled_prefix: "已启用",
    summarize_only_portfolio: "仅持仓相关",
    summarize_allow: "接收 {count}",
    summarize_block: "屏蔽 {count}",
    summarize_tz: "TZ={tz}",
    summarize_digest_off: "摘要关闭",
    summarize_digest_count: "摘要 {count} 个",
    summarize_price: "⚡{value}%",
    summarize_immediate: "即时 {count}",
    summarize_quiet: "🌙{from}–{to}",
    manual_channel_placeholder: "渠道",
    manual_user_placeholder: "账号 ID",
    manual_scope_placeholder: "会话场景（可选）",
    manual_load: "载入",
    detail_title: "细调 {channel} · {label}",
    detail_hint: "启用/关闭回上方列表切换",
    portfolio_only: "仅持仓相关",
    min_severity: "最低严重度",
    allow_kinds_label: "接收的事件类型（留空 = 全部）",
    block_kinds_label: "屏蔽的事件类型（优先级高于接收范围）",
    cadence_title: "推送节奏（按用户主体；留空 = 沿用全局）",
    timezone_label: "时区（IANA，例如 Asia/Shanghai、America/New_York）",
    timezone_placeholder: "留空 → 沿用全局时区",
    digest_label: "摘要时刻（本地 HH:MM；未设置 = 沿用全局，清空 = 关闭摘要）",
    digest_inherit_global: "当前：沿用全局摘要时刻",
    digest_off_badge: "摘要关闭（只接收即时推送）",
    digest_remove_title: "移除",
    digest_add_button: "+ 添加",
    digest_reset_global: "恢复全局",
    digest_reset_global_title: "清掉自定义 → 沿用全局摘要时刻",
    digest_mute_button: "关闭摘要",
    digest_mute_title: "清空摘要时刻，即关闭摘要",
    digest_quiet_warning: "⚠️ 部分时刻落在勿扰时段 {from}–{to} 内，这些摘要不会触发；改时间或缩短勿扰区间。",
    price_label: "价格异动即时推送阈值（绝对百分比，0<x≤50；留空 = 沿用全局；数值越低越敏感，如 3.5）",
    price_placeholder: "留空 → 沿用全局价格异动阈值",
    immediate_label: "强制按高优先级即时推送的事件类型（命中后直接即时发送）",
    quiet_section: "勿扰时段",
    quiet_enable_button: "启用（默认 00:00–08:00）",
    quiet_disable_button: "关闭勿扰",
    quiet_from: "从",
    quiet_to: "到",
    quiet_hint: "本地 HH:MM（按偏好时区解释，开始晚于结束表示跨午夜）",
    quiet_invalid: "开始时间和结束时间相同会形成空区间，无法保存；改成不同时刻或关闭勿扰。",
    quiet_exempt_hint: "勿扰豁免事件类型（命中后即使在勿扰时段内仍立即推送，例如财报发布）",
    dirty_label: "未保存改动",
    save_detail_button: "保存细调",
    save_detail_saving: "保存中…",
    save_success: "已保存 {channel} · {label} 的推送偏好，下一条事件即刻生效",
  },
}

const EN: typeof ZH = {
  page: {
    title: "Notification log",
    window_label: "Window",
    channel_label: "Channel",
    user_label: "User",
    all_users: "All users",
    refresh_button: "Refresh",
    refreshing_button: "Refreshing…",
    summary_total: "24h total",
    summary_sent: "Sent",
    summary_failed: "Send failures",
    summary_skipped: "Skipped",
    summary_duplicate: "Duplicates",
    summary_users: "Users covered",
    histogram_title: "24h push frequency (one bucket per hour, left→right = old→new)",
    histogram_hour_suffix: "h",
    histogram_tooltip: "{ts}\nTotal {total} · sent {sent} · failed {failed} · skipped {skipped}",
    legend_sent: "Sent",
    legend_failed: "Failed",
    legend_skipped: "Skipped",
    list_caption: "Push records (up to {limit}, newest first)",
    list_count: "{count} total",
    col_time: "Time",
    col_user: "User",
    col_channel: "Channel",
    col_event: "Event kind",
    col_job: "Job",
    col_send_status: "Send status",
    col_summary: "Summary",
    empty_records: "No matching push records in this window.",
    drawer_close: "Close",
    drawer_label_source: "Source",
    drawer_label_event_kind: "Event kind",
    drawer_label_user: "User",
    drawer_label_channel: "Channel",
    drawer_label_channel_scope: "Conversation context",
    drawer_label_target: "Target",
    drawer_label_exec_status: "Execution",
    drawer_label_send_status: "Delivery",
    drawer_label_should_deliver: "Delivery decision",
    drawer_label_delivered: "Actually delivered",
    drawer_label_job_id: "Job ID",
    drawer_response_preview: "Response preview",
    drawer_error: "Error",
    drawer_detail: "Detail",
  },
  send_status: {
    all: "All send statuses",
    sent: "Sent",
    dryrun: "Dry run",
    queued: "Queued",
    quiet_held: "Quiet-hours hold",
    filtered: "Filtered by preferences",
    capped: "Capped",
    cooled_down: "Cooled down",
    price_capped: "Price capped",
    price_cooled_down: "Price cooled down",
    omitted: "Digest omitted",
    skipped_noop: "Skipped (no match/queued)",
    skipped_error: "Skipped (execution failed)",
    send_failed: "Send failed",
    failed: "Send failed (event)",
    target_resolution_failed: "Target resolution failed",
    duplicate_suppressed: "Duplicate suppressed",
  },
  exec_status: {
    all: "All execution statuses",
    completed: "Success",
    noop: "No match",
    execution_failed: "Execution failed",
  },
  channel: {
    all: "All channels",
    feishu: "Feishu",
  },
  source: {
    cron: "Cron",
    event: "Event",
  },
  event_kind: {
    earnings_upcoming: "Earnings upcoming",
    earnings_released: "Earnings released",
    earnings_call_transcript: "Earnings call",
    news_critical: "Critical news",
    price_alert: "Price alert",
    weekly52_high: "52w high",
    weekly52_low: "52w low",
    dividend: "Dividend",
    split: "Split",
    sec_filing: "SEC filing",
    analyst_grade: "Analyst rating",
    macro_event: "Macro event",
    social_post: "Social post",
  },
  prefs: {
    title: "Notification preferences (per user identity)",
    subtitle: "Top: one-click enable/disable, saved automatically on toggle. Bottom: pick a user identity to fine-tune severity and event-type scope.",
    refresh_button: "Refresh",
    actor_list_label: "User identities",
    actor_loading: "Loading…",
    actor_empty: "No user identities yet (fill in the fields below, or send a message through the channel first).",
    saving_label: "Saving…",
    pushing_label: "On",
    off_label: "Off",
    summarize_disabled: "Disabled",
    summarize_enabled_prefix: "Enabled",
    summarize_only_portfolio: "portfolio only",
    summarize_allow: "Allowed {count}",
    summarize_block: "Blocked {count}",
    summarize_tz: "TZ={tz}",
    summarize_digest_off: "Digest off",
    summarize_digest_count: "Digests {count}",
    summarize_price: "⚡{value}%",
    summarize_immediate: "Immediate {count}",
    summarize_quiet: "🌙{from}–{to}",
    manual_channel_placeholder: "Channel",
    manual_user_placeholder: "Account ID",
    manual_scope_placeholder: "Context (optional)",
    manual_load: "Load",
    detail_title: "Fine-tune {channel} · {label}",
    detail_hint: "Toggle enable/disable from the list above.",
    portfolio_only: "Portfolio only",
    min_severity: "Min severity",
    allow_kinds_label: "Event types to receive (empty = all)",
    block_kinds_label: "Muted event types (overrides receive list)",
    cadence_title: "Push cadence (per user identity; empty = inherit global)",
    timezone_label: "Timezone (IANA, e.g. Asia/Shanghai, America/New_York)",
    timezone_placeholder: "Empty → inherit global timezone",
    digest_label:
      "Digest slots (local HH:MM; no custom slots = inherit global; all slots cleared = digest off)",
    digest_inherit_global: "Current: inheriting global digest slots",
    digest_off_badge: "Digest off (immediate pushes only)",
    digest_remove_title: "Remove",
    digest_add_button: "+ Add",
    digest_reset_global: "Reset to global",
    digest_reset_global_title: "Clear custom slots → inherit global digest slots",
    digest_mute_button: "Digest off",
    digest_mute_title: "Clear all digest slots — turn digests off",
    digest_quiet_warning:
      "⚠️ Some slots fall inside quiet hours {from}–{to}; those digests will not run. Move the slots or shorten quiet hours.",
    price_label: "Price-alert immediate threshold (absolute %, 0<x≤50; empty = inherit global; lower values are more sensitive, e.g. 3.5)",
    price_placeholder: "Empty → inherit global price-alert threshold",
    immediate_label:
      "Event types forced into high-priority immediate delivery",
    quiet_section: "Quiet hours",
    quiet_enable_button: "Enable (default 00:00–08:00)",
    quiet_disable_button: "Disable",
    quiet_from: "From",
    quiet_to: "To",
    quiet_hint: "Local HH:MM (interpreted in the selected timezone; start after end means it crosses midnight)",
    quiet_invalid:
      "Start and end times are the same, so this empty range cannot be saved. Use distinct times or disable quiet hours.",
    quiet_exempt_hint: "Quiet-hours exemption types (sent immediately even during quiet hours, for example earnings releases)",
    dirty_label: "Unsaved changes",
    save_detail_button: "Save",
    save_detail_saving: "Saving…",
    save_success: "Saved preferences for {channel} · {label}; takes effect on the next event.",
  },
}

export const NOTIFICATIONS = makeContentProxy(ZH, EN)
export const __NOTIFICATIONS_TREES__ = { zh: ZH, en: EN } as const
