import { makeContentProxy } from "../i18n"

const ZH = {
  detail: {
    empty_title: "从左侧定位主体持仓",
    empty_description: "你可以查看特定渠道主体的投资概况，或者为其手动调整持仓记录。",
    header_title: "持仓与关注概览",
    add_button: "添加新持仓",
    empty_records_title: "暂无持仓或关注数据",
    empty_records_description: "该用户当前没有任何资产或关注记录。",
    section_holdings: "持仓",
    section_watchlist: "关注列表",
    watchlist_badge: "仅订阅推送，不计入资金",
    col_symbol: "标的",
    col_shares: "数量",
    col_avg_cost: "平均成本",
    col_total_cost: "总成本基准",
    col_actions: "操作",
    col_notes: "备注",
    watch_chip: "关注",
    strategy_label: "策略：",
    notes_label: "备注：",
    edit_button: "编辑",
    delete_button: "删除",
    delete_confirm: "确定删除 {symbol} 这条{label}记录吗？",
    delete_label_watch: "关注",
    delete_label_holding: "持仓",
    horizon_long: "长持",
    horizon_short: "短持",
    horizon_unmarked: "未标记",
    summary_title: "组合统计概况",
    summary_holdings_count: "持有标的数",
    summary_watchlist_count: "关注标的数",
    summary_total_shares: "总数量",
    summary_updated_at: "上次更新时间",
    summary_unknown: "未知",
    form_title_new: "新增持仓 / 关注",
    form_title_edit: "编辑 {symbol}",
    form_cancel: "取消",
    form_watch_only: "仅关注（无持仓，不计入资金统计）",
    field_symbol: "股票代码（Symbol）",
    field_symbol_placeholder: "AAPL",
    field_shares: "持有数量（Shares）",
    field_shares_placeholder: "10.5",
    field_avg_cost: "平均成本（Avg Cost）",
    field_avg_cost_placeholder: "-2.35 / 150.25",
    field_horizon: "持有期限倾向（Horizon）",
    field_strategy: "特殊策略（Strategy）",
    field_strategy_placeholder: "例如：现金担保卖沽 / 财报事件驱动 / 核心长期仓位",
    field_notes: "备注（Notes）",
    field_notes_placeholder: "选填",
    save_button: "保存",
    saving_button: "保存中…",
  },
}

const EN: typeof ZH = {
  detail: {
    empty_title: "Pick a holdings owner on the left",
    empty_description: "Browse a channel user's portfolio overview, or adjust their holdings manually.",
    header_title: "Holdings & watchlist",
    add_button: "Add holding",
    empty_records_title: "No holdings or watchlist entries",
    empty_records_description: "This user has no assets or watchlist records yet.",
    section_holdings: "Holdings",
    section_watchlist: "Watchlist",
    watchlist_badge: "Push subscriptions only — not counted toward capital",
    col_symbol: "Symbol",
    col_shares: "Shares",
    col_avg_cost: "Avg cost",
    col_total_cost: "Total cost basis",
    col_actions: "Actions",
    col_notes: "Notes",
    watch_chip: "Watch",
    strategy_label: "Strategy: ",
    notes_label: "Notes: ",
    edit_button: "Edit",
    delete_button: "Delete",
    delete_confirm: "Delete the {label} record for {symbol}?",
    delete_label_watch: "watchlist",
    delete_label_holding: "holding",
    horizon_long: "Long-term",
    horizon_short: "Short-term",
    horizon_unmarked: "Unset",
    summary_title: "Portfolio summary",
    summary_holdings_count: "Held symbols",
    summary_watchlist_count: "Watchlist symbols",
    summary_total_shares: "Total shares",
    summary_updated_at: "Last updated",
    summary_unknown: "Unknown",
    form_title_new: "Add holding / watchlist",
    form_title_edit: "Edit {symbol}",
    form_cancel: "Cancel",
    form_watch_only: "Watch only (no position, excluded from capital totals)",
    field_symbol: "Symbol",
    field_symbol_placeholder: "AAPL",
    field_shares: "Shares",
    field_shares_placeholder: "10.5",
    field_avg_cost: "Avg cost",
    field_avg_cost_placeholder: "-2.35 / 150.25",
    field_horizon: "Holding horizon",
    field_strategy: "Strategy",
    field_strategy_placeholder: "e.g. cash-secured puts / earnings event / core long-term position",
    field_notes: "Notes",
    field_notes_placeholder: "Optional",
    save_button: "Save",
    saving_button: "Saving…",
  },
}

export const PORTFOLIO = makeContentProxy(ZH, EN)
export const __PORTFOLIO_TREES__ = { zh: ZH, en: EN } as const
