import { makeContentProxy } from "../i18n"

const ZH = {
  shell: {
    current_user: "当前用户",
    portfolio_button: "持仓",
    portfolio_title: "跳到该用户的持仓页",
    profiles_button: "画像",
    profiles_title: "跳到该用户的公司画像",
    new_task_button: "推送任务",
    new_task_title: "为该用户新建推送任务",
  },
  list: {
    title: "会话",
    subtitle: "按渠道查看会话，并打开对应历史",
    isolation_hint: "不同渠道的用户 ID 相互独立，无法共享上下文。",
    search_placeholder: "搜索用户名",
    channel_all: "全部渠道",
    channel_unknown: "未知",
    empty_title: "还没有会话",
    empty_description: "打开一个用户会话后，历史记录会出现在这里。",
    me_default_badge: "默认",
    last_message_empty: "暂无消息",
    group_shared_badge: "群共享",
    history_count: "{count} 条历史记录",
    relative: {
      just_now: "刚刚",
      minutes_ago: "{count} 分钟前",
      hours_ago: "{count} 小时前",
      days_ago: "{count} 天前",
    },
  },
  chat: {
    empty_open_title: "从左侧打开一个会话",
    empty_open_description: "你可以查看共享会话历史，或者新建一个用户会话开始和 Hone 对话。",
    header_subtitle_group: "共享群会话历史（当前为只读浏览）",
    header_subtitle_direct: "实时流式响应与定时消息推送",
    status_online: "在线",
    status_processing: "处理中",
    no_messages_title: "暂无历史消息",
    no_messages_hint: "先发送一条消息，或者等待定时任务推送。",
    slash_eyebrow: "技能触发",
    slash_skill_search_label: "/skill",
    slash_skill_search_hint: "搜索并触发技能",
    slash_no_match: "没有找到匹配技能，继续输入更准确的关键词。",
    slash_aliases_prefix: "别名：",
    composer_placeholder: '给 Hone 发消息，或输入 "/skill 关键词" 搜索并触发技能…',
    send_button: "发送",
    stop_button: "停止",
    stop_title: "停止",
    dismiss_title: "关闭",
    conversation_compacted: "会话已压缩",
    scheduled_label: "定时任务",
    pending: {
      queued: "发送中",
      thinking: "思考中",
      running: "执行中",
      streaming: "输出中",
      error: "出错了",
      timeout: "请求超时",
    },
  },
}

const EN: typeof ZH = {
  shell: {
    current_user: "Current user",
    portfolio_button: "Holdings",
    portfolio_title: "Open this user's holdings tab",
    profiles_button: "Profile",
    profiles_title: "Open this user's company profiles",
    new_task_button: "New task",
    new_task_title: "Create a push task for this user",
  },
  list: {
    title: "Sessions",
    subtitle: "Browse sessions by channel and open their history.",
    isolation_hint: "User IDs are isolated per channel — context is not shared across channels.",
    search_placeholder: "Search user",
    channel_all: "All channels",
    channel_unknown: "Unknown",
    empty_title: "No sessions yet",
    empty_description: "Open a user session and its history will appear here.",
    me_default_badge: "Default",
    last_message_empty: "No messages",
    group_shared_badge: "Shared",
    history_count: "{count} history entries",
    relative: {
      just_now: "just now",
      minutes_ago: "{count} min ago",
      hours_ago: "{count} h ago",
      days_ago: "{count} d ago",
    },
  },
  chat: {
    empty_open_title: "Open a session on the left",
    empty_open_description: "Browse shared session history, or start a new user session and chat with Hone.",
    header_subtitle_group: "Shared group session history (view only).",
    header_subtitle_direct: "Live streaming responses and scheduled push messages.",
    status_online: "Online",
    status_processing: "Processing",
    no_messages_title: "No messages yet",
    no_messages_hint: "Send a message, or wait for a scheduled push to arrive.",
    slash_eyebrow: "Skill command",
    slash_skill_search_label: "/skill",
    slash_skill_search_hint: "Search and run skills",
    slash_no_match: "No matching skill — keep typing a more specific keyword.",
    slash_aliases_prefix: "Aliases:",
    composer_placeholder: 'Message Hone, or type "/skill <keyword>" to search and run a skill…',
    send_button: "Send",
    stop_button: "Stop",
    stop_title: "Stop",
    dismiss_title: "Close",
    conversation_compacted: "Conversation compacted",
    scheduled_label: "Scheduled",
    pending: {
      queued: "Sending",
      thinking: "Thinking",
      running: "Running",
      streaming: "Streaming",
      error: "Error",
      timeout: "Timed out",
    },
  },
}

export const SESSIONS = makeContentProxy(ZH, EN)
export const __SESSIONS_TREES__ = { zh: ZH, en: EN } as const
