// admin-content/settings.ts — bilingual labels for the Settings page.
//
// Only strings consumed by `pages/settings.tsx` belong here. Both ZH and EN
// trees share the exact same shape — `structure.test.ts` enforces parity.

import { makeContentProxy } from "../i18n";

const ZH = {
  language: {
    title: "界面语言",
    subtitle:
      "选择控制台语言。保存后写入 config.yaml，所有连接到该后端的设备首次加载使用此语言。",
    option_zh: "中文",
    option_en: "English",
    save: "保存",
    saving: "保存中…",
    saved: "已保存",
    save_failed: "保存失败",
    no_change: "未更改",
    note: "侧边栏切换器只影响当前设备，本设置才会写入 config.yaml 决定其他设备的默认语言。",
  },
  tabs: {
    agent: "Agent",
    data: "数据源",
    notify: "通知",
    channel: "渠道",
    invite: "白名单",
  },
  agent: {
    title: "基础设置",
    subtitle:
      "选择 Agent 引擎并配置相关参数，保存后写入 config.yaml 并刷新运行时配置快照。",
    current_badge: "当前",
    hone_cloud: {
      name: "Hone Cloud",
      description:
        "使用 hone-claw.com 托管的用户端配置和生产对话服务，可填写用户 API Key 或自定义服务地址。",
      base_url_label: "服务地址",
      model_label: "模型",
      api_key_label: "API Key",
      contact_note: "如需加入白名单或获取 API Key，请联系 bm@hone-claw.com。",
      hide: "隐藏",
      show: "显示",
      test_connection: "测试连通",
      testing: "测试中…",
      connection_testing_status: "Hone Cloud 连通测试中，请稍候…",
      save: "保存",
      saving: "保存中…",
    },
    multi_agent: {
      name: "Multi-Agent",
      description:
        "Search Agent 使用 MiniMax 工具调用，Answer Agent 通过 OpenAI 兼容接口收束回复。",
      search_title: "Search Agent (MiniMax / OpenAI-compatible)",
      answer_title: "Answer Agent (OpenAI-compatible)",
      test_search: "测试 Search Agent",
      test_answer: "测试 Answer Agent",
      check_opencode: "检查 opencode",
      testing: "测试中…",
      checking: "检测中…",
      hide: "隐藏",
      show: "显示",
    },
    openai: {
      name: "OpenCode ACP",
      description:
        "通过本机 opencode acp 启动 OpenCode；可留空继承本机 opencode 配置，或在 Hone 侧覆盖 OpenAI-compatible 端点。",
      base_url_label: "Base URL",
      model_label: "主模型",
      api_key_label: "API Key",
      auxiliary_title: "辅助模型链路",
      auxiliary_subtitle:
        "用于心跳检测、会话压缩等后台辅助任务，支持独立的 OpenAI-compatible Base URL / API Key / Model。",
      auxiliary_url_label: "Auxiliary Base URL",
      auxiliary_model_label: "Auxiliary Model",
      auxiliary_apikey_label: "Auxiliary API Key",
      profiles_title: "模型用途路由",
      profiles_subtitle:
        "按用途选择模型标识；运行时会用对应配置档的服务商、模型和参数发起请求。",
      profiles_default_label: "默认对话",
      profiles_auxiliary_label: "辅助任务",
      profiles_polish_label: "消息润色",
      profiles_news_label: "新闻分类",
      profiles_filing_label: "公告摘要",
      profiles_earnings_label: "财报质检",
      profiles_digest_pass1_label: "Digest 初筛",
      profiles_digest_pass2_label: "Digest 个性化",
      profiles_digest_dedupe_label: "Digest 去重",
      profiles_mainline_label: "投资主线摘要",
      profiles_provider_label: "Provider",
      profiles_model_label: "Model",
      profiles_max_tokens_label: "Max tokens",
      profiles_temperature_label: "Temperature",
      profiles_top_p_label: "Top P",
      profiles_reasoning_label: "Reasoning",
      profiles_reasoning_tokens_label: "Reasoning tokens",
      profiles_json_label: "JSON",
      hide: "隐藏",
      show: "显示",
      test_connection: "测试连通",
      test_auxiliary: "测试辅助链路",
      testing: "测试中…",
      auxiliary_testing_status: "辅助链路连通测试中，请稍候…",
      connection_testing_status: "连通测试中，请稍候…",
      save: "保存",
      saving: "保存中…",
    },
    codex_acp: {
      name: "Codex ACP",
      description_prefix: "使用 ",
      description_code: "codex-acp",
      description_suffix:
        " 驱动当前 Agent，会话实际走 ACP 链路而不是 multi-agent。",
      runtime_note:
        "设置会写入 config.yaml 并刷新运行时配置快照；如果监听进程仍显示旧 Agent 引擎，请确认内置后端已按新配置重启。",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
    gemini_cli: {
      name: "Gemini CLI",
      description_prefix: "使用本机安装的 ",
      description_code: "gemini",
      description_suffix: " 命令行 Agent",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
    codex_cli: {
      name: "Codex",
      description_prefix: "使用本机安装的 ",
      description_code: "codex",
      description_suffix: " 命令行 Agent",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
  },
  data: {
    title: "API 配置",
    subtitle: "配置各类数据源和搜索服务的密钥。支持多 Key 轮换及自动重试。",
    fmp: {
      name: "金融数据 API（Financial Modeling Prep）",
      description: "用于获取实时股票、报表等金融核心数据",
      key_placeholder: "FMP API Key",
      remove: "删除",
      add_key: "+ 添加 Key",
      save: "保存 FMP",
      saving: "保存中…",
      saved: "已保存 FMP API Key 列表，内置后端已重启生效",
    },
    tavily: {
      name: "搜索 API（Tavily）",
      description: "用于联网获取最新信息、文章、网页内容",
      key_placeholder: "tvly-...",
      remove: "删除",
      add_key: "+ 添加 Key",
      save: "保存 Tavily",
      saving: "保存中…",
      saved: "已保存 Tavily API Key 列表，内置后端已重启生效",
    },
  },
  notify: {
    title: "通知推送偏好",
    subtitle:
      "代任意用户主体调整事件推送策略。终端用户自己也可以在渠道里用自然语言调整。",
  },
  channel: {
    title: "渠道设置",
    subtitle: "开启后 Hone 会通过对应渠道监听消息并进行 Agent 响应。",
    refresh: "刷新配置",
    common: {
      chat_scope_label: "会话范围",
      allow_from_label: "允许用户",
      allow_emails_label: "允许邮箱",
      allow_mobiles_label: "允许的手机号",
      allow_open_ids_label: "允许 OpenID",
      target_handle_label: "监听账号",
      csv_placeholder: "逗号分隔；留空表示全部允许",
    },
    feishu: {
      name: "飞书（Feishu）",
      app_id_label: "App ID",
      app_id_placeholder: "cli_...",
      app_secret_label: "App Secret",
      app_secret_placeholder: "Secret",
      hide: "隐藏",
      show: "显示",
    },
    discord: {
      name: "Discord",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Discord Bot Token",
      hide: "隐藏",
      show: "显示",
    },
    telegram: {
      name: "Telegram",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Token",
      hide: "隐藏",
      show: "显示",
    },
    imessage: {
      name: "iMessage",
      warning: "需要完全磁盘访问权限",
    },
    sync_note:
      "保存后配置文件立即更新；CLI 启动的监听进程需重启后应用启停变化。",
    save: "同步全部渠道",
    saving: "同步中…",
  },
  invite: {
    title: "Web 用户白名单",
    subtitle:
      "新增手机号会同步创建一个 `web` 用户。用户通过 `/chat` 使用手机号和短信验证码登录后，复用现有 12 次对话额度限制；历史邀请码保留用于兼容和管理。",
    refresh: "刷新",
    phone_label: "手机号",
    phone_placeholder: "输入要加入白名单的手机号",
    create: "加入白名单",
    creating: "加入中…",
    phone_required: "请输入手机号",
    created: "已将 {phone} 加入白名单（兼容邀请码 {code}）",
    created_copied: "已将 {phone} 加入白名单，并复制兼容邀请码 {code}",
    created_with_api_key:
      "已将 {phone} 加入白名单，并生成兼容邀请码 {code} 和 API Key {apiKey}",
    created_with_api_key_copied:
      "已将 {phone} 加入白名单，并生成兼容邀请码 {code} 和 API Key；均已复制",
    copied: "已复制邀请码 {code}",
    copy_unsupported: "当前环境不支持复制",
    disable_confirm:
      "停用 {userId} 的白名单后，现有 Web 登录态会立即失效。继续吗？",
    reset_confirm:
      "将为 {userId} 生成新兼容邀请码，并让旧邀请码和现有 Web 登录态立即失效。继续吗？",
    api_key_reset_confirm:
      "将为 {userId} 生成新的 API Key，旧 API Key 会立即失效，但不会清理登录态。继续吗？",
    reset_copied_suffix: "{message}，新邀请码已复制",
    api_key_copied: "API Key 已复制。明文只显示一次，请妥善保存。",
    table: {
      code: "邀请码",
      phone: "手机号",
      web_user: "Web 用户",
      status: "状态",
      api_key: "API Key",
      sessions: "登录态",
      remaining: "剩余次数",
      last_login: "最近登录",
      actions: "操作",
      empty: "还没有加入任何白名单用户。",
      phone_unbound: "未绑定",
      enabled: "已启用",
      disabled: "已停用",
      unlimited: "不限",
      never_logged_in: "未登录",
      api_key_missing: "未生成",
      copy: "复制",
      reset: "重置",
      resetting: "重置中…",
      api_key_get: "获取 Key",
      api_key_getting: "获取中…",
      api_key_reset: "重置 Key",
      api_key_resetting: "重置中…",
      enable: "启用",
      enabling: "启用中…",
      disable: "停用",
      disabling: "停用中…",
    },
  },
};

const EN: typeof ZH = {
  language: {
    title: "Language",
    subtitle:
      "Choose the console language. Saving writes to config.yaml — all devices connecting to this backend will pick up this default on first load.",
    option_zh: "中文",
    option_en: "English",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    save_failed: "Save failed",
    no_change: "No change",
    note: "The sidebar switcher only affects the current device. This setting writes to config.yaml and decides the default language on other devices.",
  },
  tabs: {
    agent: "Agent",
    data: "Data sources",
    notify: "Notifications",
    channel: "Channels",
    invite: "Whitelist",
  },
  agent: {
    title: "Core settings",
    subtitle:
      "Pick the agent engine and configure its parameters. Saving writes config.yaml and refreshes the runtime config snapshot.",
    current_badge: "Active",
    hone_cloud: {
      name: "Hone Cloud",
      description:
        "Uses the hone-claw.com hosted user configuration and production chat service. Enter a user API key or customize the service URL.",
      base_url_label: "Service URL",
      model_label: "Model",
      api_key_label: "API Key",
      contact_note:
        "Contact bm@hone-claw.com to join the whitelist or get an API key.",
      hide: "Hide",
      show: "Show",
      test_connection: "Test connection",
      testing: "Testing…",
      connection_testing_status: "Testing Hone Cloud connection, please wait…",
      save: "Save",
      saving: "Saving…",
    },
    multi_agent: {
      name: "Multi-Agent",
      description:
        "Search Agent uses MiniMax function calling; Answer Agent finalizes the reply through an OpenAI-compatible route.",
      search_title: "Search Agent (MiniMax / OpenAI-compatible)",
      answer_title: "Answer Agent (OpenAI-compatible)",
      test_search: "Test Search Agent",
      test_answer: "Test Answer Agent",
      check_opencode: "Check opencode",
      testing: "Testing…",
      checking: "Checking…",
      hide: "Hide",
      show: "Show",
    },
    openai: {
      name: "OpenCode ACP",
      description:
        "Starts local OpenCode via opencode acp. Leave fields blank to inherit local opencode config, or override the OpenAI-compatible endpoint from Hone.",
      base_url_label: "Base URL",
      model_label: "Primary model",
      api_key_label: "API Key",
      auxiliary_title: "Auxiliary model path",
      auxiliary_subtitle:
        "Used for heartbeat checks, session compaction, and other background helpers. Accepts an independent OpenAI-compatible Base URL / API Key / Model.",
      auxiliary_url_label: "Auxiliary Base URL",
      auxiliary_model_label: "Auxiliary Model",
      auxiliary_apikey_label: "Auxiliary API Key",
      profiles_title: "Model route profiles",
      profiles_subtitle:
        "Pick a model identifier for each use case. Runtime calls use the matching profile provider, model, and parameters.",
      profiles_default_label: "Default chat",
      profiles_auxiliary_label: "Auxiliary tasks",
      profiles_polish_label: "Message polish",
      profiles_news_label: "News classifier",
      profiles_filing_label: "Filing summary",
      profiles_earnings_label: "Earnings review",
      profiles_digest_pass1_label: "Digest pass 1",
      profiles_digest_pass2_label: "Digest pass 2",
      profiles_digest_dedupe_label: "Digest dedupe",
      profiles_mainline_label: "Mainline summary",
      profiles_provider_label: "Provider",
      profiles_model_label: "Model",
      profiles_max_tokens_label: "Max tokens",
      profiles_temperature_label: "Temperature",
      profiles_top_p_label: "Top P",
      profiles_reasoning_label: "Reasoning",
      profiles_reasoning_tokens_label: "Reasoning tokens",
      profiles_json_label: "JSON",
      hide: "Hide",
      show: "Show",
      test_connection: "Test connection",
      test_auxiliary: "Test auxiliary route",
      testing: "Testing…",
      auxiliary_testing_status: "Testing auxiliary route connection, please wait…",
      connection_testing_status: "Testing connection, please wait…",
      save: "Save",
      saving: "Saving…",
    },
    codex_acp: {
      name: "Codex ACP",
      description_prefix: "Drives the current agent via ",
      description_code: "codex-acp",
      description_suffix:
        ". Sessions run over the ACP link instead of multi-agent.",
      runtime_note:
        "Settings write to config.yaml and refresh the runtime config snapshot. If the listener still shows the old agent engine, confirm that the embedded backend restarted with the new config.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
    gemini_cli: {
      name: "Gemini CLI",
      description_prefix: "Uses the locally installed ",
      description_code: "gemini",
      description_suffix: " CLI agent.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
    codex_cli: {
      name: "Codex",
      description_prefix: "Uses the locally installed ",
      description_code: "codex",
      description_suffix: " CLI agent.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
  },
  data: {
    title: "API configuration",
    subtitle:
      "Configure keys for data sources and search services. Multi-key rotation and auto retry are supported.",
    fmp: {
      name: "Financial data API (Financial Modeling Prep)",
      description:
        "Real-time quotes, fundamentals, and other core financial data.",
      key_placeholder: "FMP API Key",
      remove: "Remove",
      add_key: "+ Add key",
      save: "Save FMP",
      saving: "Saving…",
      saved: "FMP API keys saved; the embedded backend has restarted.",
    },
    tavily: {
      name: "Search API (Tavily)",
      description:
        "Live web search for fresh news, articles, and page content.",
      key_placeholder: "tvly-...",
      remove: "Remove",
      add_key: "+ Add key",
      save: "Save Tavily",
      saving: "Saving…",
      saved: "Tavily API keys saved; the embedded backend has restarted.",
    },
  },
  notify: {
    title: "Notification preferences",
    subtitle:
      "Adjust event push policy on behalf of any user identity. End users can also tune this from the channel via natural language.",
  },
  channel: {
    title: "Channels",
    subtitle:
      "When enabled, Hone listens for messages on the channel and replies via the agent.",
    refresh: "Refresh",
    common: {
      chat_scope_label: "Chat scope",
      allow_from_label: "Allowed users",
      allow_emails_label: "Allowed emails",
      allow_mobiles_label: "Allowed phone numbers",
      allow_open_ids_label: "Allowed OpenIDs",
      target_handle_label: "Target account",
      csv_placeholder: "Comma-separated; empty means allow all",
    },
    feishu: {
      name: "Feishu (Lark)",
      app_id_label: "App ID",
      app_id_placeholder: "cli_...",
      app_secret_label: "App Secret",
      app_secret_placeholder: "Secret",
      hide: "Hide",
      show: "Show",
    },
    discord: {
      name: "Discord",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Discord Bot Token",
      hide: "Hide",
      show: "Show",
    },
    telegram: {
      name: "Telegram",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Token",
      hide: "Hide",
      show: "Show",
    },
    imessage: {
      name: "iMessage",
      warning: "Requires Full Disk Access",
    },
    sync_note:
      "Saving updates the config file immediately; CLI-started listeners need a restart to apply enable/disable changes.",
    save: "Sync all channels",
    saving: "Syncing…",
  },
  invite: {
    title: "Web user whitelist",
    subtitle:
      "Adding a phone number creates a `web` user. Users sign in from `/chat` with phone + SMS code and share the existing 12-message daily quota. Historical invite codes are kept for compatibility and management.",
    refresh: "Refresh",
    phone_label: "Phone number",
    phone_placeholder: "Phone number to whitelist",
    create: "Add to whitelist",
    creating: "Adding…",
    phone_required: "Enter a phone number",
    created: "Added {phone} to the whitelist (compatibility invite code {code})",
    created_copied:
      "Added {phone} to the whitelist and copied compatibility invite code {code}",
    created_with_api_key:
      "Added {phone} to the whitelist with compatibility invite code {code} and API key {apiKey}",
    created_with_api_key_copied:
      "Added {phone} to the whitelist with compatibility invite code {code} and API key; both copied",
    copied: "Copied invite code {code}",
    copy_unsupported: "Clipboard not available in this environment",
    disable_confirm:
      "Disabling the whitelist entry for {userId} will immediately log out the existing web session. Continue?",
    reset_confirm:
      "This will issue a new compatibility invite code for {userId} and immediately invalidate the old code and any active web session. Continue?",
    api_key_reset_confirm:
      "This will issue a new API key for {userId}. The old API key stops working, but web sessions stay signed in. Continue?",
    reset_copied_suffix: "{message}; new invite code copied",
    api_key_copied:
      "API key copied. Plaintext is shown only once; store it securely.",
    table: {
      code: "Invite code",
      phone: "Phone",
      web_user: "Web user",
      status: "Status",
      api_key: "API Key",
      sessions: "Sessions",
      remaining: "Remaining",
      last_login: "Last login",
      actions: "Actions",
      empty: "No whitelisted web users yet.",
      phone_unbound: "Not bound",
      enabled: "Enabled",
      disabled: "Disabled",
      unlimited: "Unlimited",
      never_logged_in: "Never",
      api_key_missing: "Not generated",
      copy: "Copy",
      reset: "Reset",
      resetting: "Resetting…",
      api_key_get: "Get key",
      api_key_getting: "Getting…",
      api_key_reset: "Reset key",
      api_key_resetting: "Resetting…",
      enable: "Enable",
      enabling: "Enabling…",
      disable: "Disable",
      disabling: "Disabling…",
    },
  },
};

export const SETTINGS = makeContentProxy(ZH, EN);

// Internal — exported only for the structure parity test.
export const __SETTINGS_TREES__ = { zh: ZH, en: EN } as const;
