// admin-content/shared.ts
//
// Bilingual labels reused across the admin console: sidebar navigation, the
// locale switcher, common buttons, status pills, toast verbs, and other
// chrome-level strings. Per-page strings live in sibling files
// (admin-content/<page>.ts). Both ZH and EN trees MUST share the exact same
// shape — `structure.test.ts` enforces parity at build time.

import { makeContentProxy } from "../i18n"

const ZH = {
  brand: {
    eyebrow: "OPEN FINANCIAL CONSOLE",
    public_chat_aria: "打开用户端（端口 8088）",
  },

  nav: {
    section_workspace: "工作台",
    section_user_view: "用户视角",
    section_research: "研究",
    section_system: "系统",
    dashboard: "概览",
    sessions: "会话",
    users: "用户档案",
    tasks: "推送任务",
    notifications: "推送日志",
    schedule: "推送日程",
    research: "个股研究",
    skills: "技能管理",
    llm_audit: "LLM 审计",
    logs: "日志",
    task_health: "任务健康",
    settings: "设置",
  },

  locale: {
    switch_label: "界面语言",
    zh: "中文",
    en: "EN",
  },

  buttons: {
    save: "保存",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    confirm: "确认",
    close: "关闭",
    reload: "刷新",
    apply: "应用",
    add: "添加",
    remove: "移除",
    create: "新建",
    rename: "重命名",
    copy: "复制",
    open: "打开",
    back: "返回",
    next: "下一步",
    prev: "上一步",
    loading: "加载中…",
    saving: "保存中…",
    deleting: "删除中…",
    submit: "提交",
    submitting: "提交中…",
    retry: "重试",
    export: "导出",
    import: "导入",
    search: "搜索",
    filter: "筛选",
    clear: "清空",
    reset: "重置",
    more: "更多",
    show_more: "展开",
    show_less: "收起",
    select: "选择",
    select_all: "全选",
    deselect_all: "全不选",
    refresh: "刷新",
    view: "查看",
    details: "详情",
    yes: "是",
    no: "否",
    enabled: "启用",
    disabled: "禁用",
  },

  status: {
    running: "运行中",
    stopped: "已停止",
    starting: "启动中",
    degraded: "降级",
    unsupported: "不支持",
    pending: "等待中",
    success: "成功",
    failed: "失败",
    error: "错误",
    warning: "警告",
    info: "提示",
    active: "已启用",
    inactive: "未启用",
    online: "在线",
    offline: "离线",
    connected: "已连接",
    disconnected: "未连接",
    saved: "已保存",
    deleted: "已删除",
    updated: "已更新",
    created: "已创建",
    canceled: "已取消",
    none: "暂无",
    empty: "暂无数据",
    loading: "加载中…",
    not_set: "未设置",
    unknown: "未知",
    optional: "选填",
    required: "必填",
    all: "全部",
  },

  toast: {
    save_failed: "保存失败",
    delete_failed: "删除失败",
    load_failed: "加载失败",
    network_error: "网络错误",
    unknown_error: "未知错误",
    copy_succeeded: "已复制到剪贴板",
    copy_failed: "复制失败",
  },

  layout: {
    not_connected_title: "尚未连接到 Hone 后端",
    not_connected_hint: "请在「设置 → 后端连接」中检查 baseUrl / token 后重试。",
  },

  units: {
    items: "条",
    rows: "行",
    seconds: "秒",
    minutes: "分钟",
    hours: "小时",
    days: "天",
  },

  time: {
    just_now: "刚刚",
    seconds_ago_one: "{count} 秒前",
    seconds_ago_other: "{count} 秒前",
    minutes_ago_one: "{count} 分钟前",
    minutes_ago_other: "{count} 分钟前",
    hours_ago_one: "{count} 小时前",
    hours_ago_other: "{count} 小时前",
    days_ago_one: "{count} 天前",
    days_ago_other: "{count} 天前",
    never: "从未",
  },
}

const EN: typeof ZH = {
  brand: {
    eyebrow: "OPEN FINANCIAL CONSOLE",
    public_chat_aria: "Open public chat (port 8088)",
  },

  nav: {
    section_workspace: "Workspace",
    section_user_view: "User View",
    section_research: "Research",
    section_system: "System",
    dashboard: "Overview",
    sessions: "Sessions",
    users: "User Profiles",
    tasks: "Push Tasks",
    notifications: "Push Logs",
    schedule: "Push Schedule",
    research: "Equity Research",
    skills: "Skills",
    llm_audit: "LLM Audit",
    logs: "Logs",
    task_health: "Task Health",
    settings: "Settings",
  },

  locale: {
    switch_label: "Language",
    zh: "中文",
    en: "EN",
  },

  buttons: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    confirm: "Confirm",
    close: "Close",
    reload: "Reload",
    apply: "Apply",
    add: "Add",
    remove: "Remove",
    create: "Create",
    rename: "Rename",
    copy: "Copy",
    open: "Open",
    back: "Back",
    next: "Next",
    prev: "Previous",
    loading: "Loading…",
    saving: "Saving…",
    deleting: "Deleting…",
    submit: "Submit",
    submitting: "Submitting…",
    retry: "Retry",
    export: "Export",
    import: "Import",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    reset: "Reset",
    more: "More",
    show_more: "Show more",
    show_less: "Show less",
    select: "Select",
    select_all: "Select all",
    deselect_all: "Deselect all",
    refresh: "Refresh",
    view: "View",
    details: "Details",
    yes: "Yes",
    no: "No",
    enabled: "Enabled",
    disabled: "Disabled",
  },

  status: {
    running: "Running",
    stopped: "Stopped",
    starting: "Starting",
    degraded: "Degraded",
    unsupported: "Unsupported",
    pending: "Pending",
    success: "Success",
    failed: "Failed",
    error: "Error",
    warning: "Warning",
    info: "Info",
    active: "Enabled",
    inactive: "Disabled",
    online: "Online",
    offline: "Offline",
    connected: "Connected",
    disconnected: "Disconnected",
    saved: "Saved",
    deleted: "Deleted",
    updated: "Updated",
    created: "Created",
    canceled: "Canceled",
    none: "None",
    empty: "No data",
    loading: "Loading…",
    not_set: "Not set",
    unknown: "Unknown",
    optional: "Optional",
    required: "Required",
    all: "All",
  },

  toast: {
    save_failed: "Save failed",
    delete_failed: "Delete failed",
    load_failed: "Load failed",
    network_error: "Network error",
    unknown_error: "Unknown error",
    copy_succeeded: "Copied to clipboard",
    copy_failed: "Copy failed",
  },

  layout: {
    not_connected_title: "Not connected to the Hone backend",
    not_connected_hint:
      "Check baseUrl / token under Settings → Backend Connection and retry.",
  },

  units: {
    items: "items",
    rows: "rows",
    seconds: "s",
    minutes: "min",
    hours: "h",
    days: "d",
  },

  time: {
    just_now: "just now",
    seconds_ago_one: "{count} second ago",
    seconds_ago_other: "{count} seconds ago",
    minutes_ago_one: "{count} minute ago",
    minutes_ago_other: "{count} minutes ago",
    hours_ago_one: "{count} hour ago",
    hours_ago_other: "{count} hours ago",
    days_ago_one: "{count} day ago",
    days_ago_other: "{count} days ago",
    never: "never",
  },
}

export const SHARED = makeContentProxy(ZH, EN)

// Internal — exported only for the structure parity test in structure.test.ts.
export const __SHARED_TREES__ = { zh: ZH, en: EN } as const
