import { makeContentProxy } from "../i18n"

const ZH = {
  list: {
    title: "任务中心",
    subtitle: "管理定时触发的工作流（东八区）",
    new_button: "新建",
    not_scheduled: "未调度",
    empty_title: "目前没有定时任务",
    empty_description: "点击右上角新建任务可以开始使用。",
    every_30_minutes: "每 30 分钟",
    heartbeat_badge: "心跳检测",
    next_run_label: "下一次：",
    next_run_heartbeat: "每 30 分钟检查一次",
  },
  detail: {
    empty_title: "从左侧选择一个任务",
    empty_description: "你可以查看、新建或管理你的定时触发工作流。",
    new_title: "新建定时任务",
    fallback_title: "任务详情",
    new_subtitle: "设定触发条件和 Agent 执行动作",
    id_prefix: "ID: {id}",
    delete_button: "删除",
    delete_confirm: "确定要删除此任务吗？",
    disable_button: "停用任务",
    enable_button: "启用任务",
    field_name: "任务名称",
    field_name_placeholder: "例如：每日大盘早报",
    field_user_id: "归属账号",
    field_user_id_placeholder: "输入当前任务归属的账号 ID",
    field_channel: "触发渠道",
    channel_imessage_disabled: "iMessage（已禁用）",
    field_channel_scope: "群聊上下文（可选）",
    field_channel_scope_placeholder: "私聊留空；群聊填写群组或频道 ID",
    field_hour: "执行时间（小时）",
    field_hour_placeholder: "0 - 23",
    field_minute: "执行时间（分钟）",
    field_minute_placeholder: "0 - 59",
    field_repeat: "重复频率",
    repeat_once: "单次（Once）",
    repeat_daily: "每天（Daily）",
    repeat_workday: "工作日（Workday）",
    repeat_trading_day: "交易日（Trading Day）",
    repeat_holiday: "节假日（Holiday）",
    repeat_weekly: "每周（Weekly）",
    repeat_heartbeat: "心跳检测（Heartbeat）",
    heartbeat_help: "心跳任务会每 30 分钟检查一次条件，不需要指定具体时刻。",
    field_weekday: "周几执行（针对 Weekly）",
    field_weekday_placeholder: "0（周一）- 6（周日）",
    weekday_help: "取值 0 - 6，其中 0 代表星期一",
    field_target: "发送目标",
    field_target_placeholder: "留空则发送给归属账号",
    field_target_help: "如需发到特定群聊，可填写群组 ID、频道 ID 或手机号。",
    field_prompt: "任务指令",
    field_prompt_placeholder: "发送给 Agent 的明确指令，例如：总结昨天纳斯达克市场的核心科技股走势并提取关注点。",
    save_button: "保存设置",
    saving_button: "保存中…",
    history_title: "执行记录",
    history_subtitle: "所有时间统一按东八区（Asia/Shanghai）展示",
    history_count: "最近 {count} 条",
    history_empty: "暂无执行记录",
    history_col_time: "时间",
    history_col_exec: "执行状态",
    history_col_send: "发送结果",
    history_col_hit: "命中条件",
    history_col_delivered: "已发送",
    history_col_summary: "摘要",
    yes: "是",
    no: "否",
    parse_kind_prefix: "parse_kind:",
    exec: {
      completed: "执行成功",
      noop: "未命中",
      execution_failed: "执行失败",
      unknown: "未知",
    },
    send: {
      sent: "已发送",
      skipped_noop: "未发送（未命中）",
      skipped_error: "未发送（执行失败）",
      send_failed: "发送失败",
      target_resolution_failed: "目标解析失败",
      duplicate_suppressed: "已拦截重复发送",
      unknown: "未知",
    },
  },
}

const EN: typeof ZH = {
  list: {
    title: "Tasks",
    subtitle: "Manage scheduled workflows (Asia/Shanghai).",
    new_button: "New",
    not_scheduled: "Not scheduled",
    empty_title: "No scheduled tasks",
    empty_description: "Use the New button to create your first task.",
    every_30_minutes: "Every 30 min",
    heartbeat_badge: "Heartbeat",
    next_run_label: "Next:",
    next_run_heartbeat: "Checks every 30 minutes",
  },
  detail: {
    empty_title: "Select a task on the left",
    empty_description: "View, create, or manage your scheduled workflows.",
    new_title: "New scheduled task",
    fallback_title: "Task detail",
    new_subtitle: "Configure trigger conditions and the agent action",
    id_prefix: "ID: {id}",
    delete_button: "Delete",
    delete_confirm: "Delete this task?",
    disable_button: "Disable",
    enable_button: "Enable",
    field_name: "Task name",
    field_name_placeholder: "e.g. Daily market briefing",
    field_user_id: "Owner account",
    field_user_id_placeholder: "Account ID that owns this task",
    field_channel: "Channel",
    channel_imessage_disabled: "iMessage (disabled)",
    field_channel_scope: "Group context (optional)",
    field_channel_scope_placeholder: "Leave blank for DMs, or enter the group/channel ID",
    field_hour: "Hour",
    field_hour_placeholder: "0 - 23",
    field_minute: "Minute",
    field_minute_placeholder: "0 - 59",
    field_repeat: "Repeat",
    repeat_once: "Once",
    repeat_daily: "Daily",
    repeat_workday: "Workday",
    repeat_trading_day: "Trading day",
    repeat_holiday: "Holiday",
    repeat_weekly: "Weekly",
    repeat_heartbeat: "Heartbeat",
    heartbeat_help: "Heartbeat jobs poll every 30 minutes; no specific time needed.",
    field_weekday: "Weekday (for weekly)",
    field_weekday_placeholder: "0 (Mon) - 6 (Sun)",
    weekday_help: "0 - 6, where 0 means Monday.",
    field_target: "Delivery target",
    field_target_placeholder: "Blank sends to the owner account",
    field_target_help: "For group delivery, enter the group ID, channel ID, or phone number.",
    field_prompt: "Task prompt",
    field_prompt_placeholder: "Exact prompt sent to the agent, e.g. summarize yesterday's Nasdaq tech moves and call out key tickers.",
    save_button: "Save",
    saving_button: "Saving…",
    history_title: "Execution history",
    history_subtitle: "All times shown in Asia/Shanghai.",
    history_count: "Last {count} runs",
    history_empty: "No executions yet",
    history_col_time: "Time",
    history_col_exec: "Execution",
    history_col_send: "Delivery",
    history_col_hit: "Matched",
    history_col_delivered: "Delivered",
    history_col_summary: "Summary",
    yes: "Yes",
    no: "No",
    parse_kind_prefix: "parse_kind:",
    exec: {
      completed: "Success",
      noop: "No match",
      execution_failed: "Execution failed",
      unknown: "Unknown",
    },
    send: {
      sent: "Sent",
      skipped_noop: "Skipped (no match)",
      skipped_error: "Skipped (execution failed)",
      send_failed: "Send failed",
      target_resolution_failed: "Target resolution failed",
      duplicate_suppressed: "Duplicate suppressed",
      unknown: "Unknown",
    },
  },
}

export const TASKS = makeContentProxy(ZH, EN)
export const __TASKS_TREES__ = { zh: ZH, en: EN } as const
