import { makeContentProxy } from "../i18n"

const ZH = {
  page: {
    empty_title: "先从左侧选一个用户",
    empty_description:
      "选定后会在这里横向展开持仓 / 公司画像 / 会话 / 相关研究 4 个视角，无需跨模块重复选人。",
    refresh_button: "刷新",
    tab_portfolio: "持仓",
    tab_profiles: "公司画像",
    tab_mainline: "蒸馏投资主线",
    tab_sessions: "会话",
    tab_research: "相关研究",
  },
  list: {
    title: "用户档案",
    subtitle: "合并持仓 / 画像 / 会话三处来源",
    manual_open: "手动输入",
    manual_collapse: "收起",
    search_placeholder: "搜索用户 ID / 渠道 / 场景",
    manual_channel_placeholder: "渠道，如 imessage",
    manual_user_id_placeholder: "用户 ID",
    manual_scope_placeholder: "场景，可选",
    manual_submit: "打开",
    empty_search_title: "没有匹配的用户",
    empty_search_description: "试试切换搜索词，或用上方手动输入定位特定用户主体。",
    empty_title: "暂无用户",
    empty_description:
      "还没有人产生持仓 / 画像 / 会话，先让 IM 渠道接收消息或手动添加。",
    stat_holdings: "{count} 持仓",
    stat_watchlist: "{count} 关注",
    stat_profiles: "{count} 画像",
    stat_sessions: "会话",
    stat_empty: "暂无数据",
  },
  select: {
    no_options: "暂无可选用户",
    all_label: "全部用户",
    placeholder: "选择用户",
    tag_holdings: "{count} 持仓",
    tag_profiles: "{count} 画像",
    tag_sessions: "会话",
  },
  sessions: {
    empty_title: "还没有会话记录",
    empty_description: "该用户尚未在任何渠道发起会话。",
    message_count: "{count} 条消息",
    empty_message: "(空)",
  },
  research: {
    empty_title: "该用户暂无关注的标的",
    empty_description: "先在「持仓」页里添加持仓或关注，这里会列出关联的研究任务。",
    symbols_title: "该用户的标的",
    start_for_title: "为 {symbol} 启动研究",
    symbols_hint: "点击标的可在个股研究模块直接启动新任务",
    related_title: "关联的研究任务",
    related_empty: "暂无与该用户标的相关的研究任务。点击上方标的可启动一个。",
    created_at: "创建于 {date}",
  },
  mainline: {
    loading: "加载中…",
    load_error: "加载失败：{error}",
    last_distilled_label: "上次蒸馏：",
    not_distilled: "尚未蒸馏",
    today_at: "今天 {time}",
    days_ago_one: "1 天前",
    days_ago_other: "{count} 天前",
    skipped_prefix: "跳过 {count} 只：",
    distill_button: "立即触发蒸馏",
    distilling_button: "蒸馏中…",
    distill_success: "蒸馏完成：{count} 条投资主线，跳过 {skipped} 只",
    distill_failure: "蒸馏失败：{error}",
    style_title: "整体投资风格",
    style_empty: "尚未蒸馏 — 至少需要一个公司画像。",
    holdings_title: "各持仓投资主线（{count}）",
    holdings_empty: "该用户主体持仓为空。",
    view_profile: "查看画像",
    view: "查看",
    no_profile_label: "没有公司画像",
    no_profile_hint: " — 用户需在聊天里建档。",
    profile_distill_failed: "画像存在但投资主线蒸馏失败",
    skipped_last_run: "（上次跳过）",
    retry_hint: "，点“立即触发蒸馏”重试。",
    profile_inventory_title: "公司画像清单（{count}）",
    profile_inventory_empty: "该用户主体的沙盒里还没有任何公司画像。",
    modal_title_suffix: " · 公司画像",
    modal_footer:
      "画像由用户在聊天里通过公司画像技能维护，此处只读。",
  },
}

const EN: typeof ZH = {
  page: {
    empty_title: "Pick a user on the left",
    empty_description:
      "Once selected, you'll see holdings / company profiles / sessions / related research side by side — no need to re-pick across modules.",
    refresh_button: "Refresh",
    tab_portfolio: "Holdings",
    tab_profiles: "Profiles",
    tab_mainline: "Investment mainline",
    tab_sessions: "Sessions",
    tab_research: "Research",
  },
  list: {
    title: "Users",
    subtitle: "Merged from holdings, profiles, and sessions.",
    manual_open: "Manual",
    manual_collapse: "Hide",
    search_placeholder: "Search user ID / channel / context",
    manual_channel_placeholder: "Channel, e.g. imessage",
    manual_user_id_placeholder: "User ID",
    manual_scope_placeholder: "Context, optional",
    manual_submit: "Open",
    empty_search_title: "No matching users",
    empty_search_description:
      "Try a different search term, or use manual entry above to locate a specific user.",
    empty_title: "No users yet",
    empty_description:
      "Nobody has holdings / profiles / sessions yet — connect an IM channel or add one manually.",
    stat_holdings: "{count} holdings",
    stat_watchlist: "{count} watching",
    stat_profiles: "{count} profiles",
    stat_sessions: "Sessions",
    stat_empty: "No data",
  },
  select: {
    no_options: "No users available",
    all_label: "All users",
    placeholder: "Pick a user",
    tag_holdings: "{count} holdings",
    tag_profiles: "{count} profiles",
    tag_sessions: "sessions",
  },
  sessions: {
    empty_title: "No session history",
    empty_description: "This user hasn't started a session on any channel.",
    message_count: "{count} messages",
    empty_message: "(empty)",
  },
  research: {
    empty_title: "No tickers yet for this user",
    empty_description:
      "Add holdings or a watchlist on the Holdings tab — related research tasks will show up here.",
    symbols_title: "This user's tickers",
    start_for_title: "Start research for {symbol}",
    symbols_hint: "Click a ticker to start a new task in the research module.",
    related_title: "Related research tasks",
    related_empty:
      "No research tasks tied to this user's tickers yet. Click a ticker above to start one.",
    created_at: "Created {date}",
  },
  mainline: {
    loading: "Loading…",
    load_error: "Load failed: {error}",
    last_distilled_label: "Last distilled:",
    not_distilled: "Not distilled yet",
    today_at: "Today {time}",
    days_ago_one: "1 day ago",
    days_ago_other: "{count} days ago",
    skipped_prefix: "Skipped {count}:",
    distill_button: "Distill now",
    distilling_button: "Distilling…",
    distill_success:
      "Done: {count} investment mainlines, {skipped} skipped",
    distill_failure: "Distill failed: {error}",
    style_title: "Overall investment style",
    style_empty: "Not distilled yet — at least one company profile is required.",
    holdings_title: "Per-holding mainlines ({count})",
    holdings_empty: "This user has no holdings.",
    view_profile: "View profile",
    view: "View",
    no_profile_label: "No company profile",
    no_profile_hint: " — the user needs to create one in chat.",
    profile_distill_failed:
      "Profile exists but mainline distillation failed",
    skipped_last_run: " (skipped last run)",
    retry_hint: '. Click "Distill now" to retry.',
    profile_inventory_title: "Company profile inventory ({count})",
    profile_inventory_empty:
      "This user's sandbox has no company profiles yet.",
    modal_title_suffix: " · Company profile",
    modal_footer:
      "Profiles are maintained by the user in chat through the company profile skill — read-only here.",
  },
}

export const USERS = makeContentProxy(ZH, EN)
export const __USERS_TREES__ = { zh: ZH, en: EN } as const
